In [1]:
import numpy as np

In [2]:
test_array = np.array([1,2,3,4,5],float)
print(test_array)

[ 1.  2.  3.  4.  5.]


In [3]:
type(test_array[3])

numpy.float64

In [4]:
test_array.shape # one dimention

(5,)

In [21]:
#dimension 확인
test_array.ndim

1

In [22]:
#size 확인
test_array.size

5

### reshape

In [23]:
test_matrix = [[1,2,3,4],[1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [25]:
#4x2로 만들기
np.array(test_matrix).reshape(-1,2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

### flatten

In [26]:
# one dimension으로 만들기
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8])

### something_like

In [32]:
test_matrix = np.arange(30).reshape(5,6)
print(test_matrix)
print(np.ones_like(test_matrix))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


### random sampling

In [33]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[ 0.68247198,  0.26181172,  0.52531747,  0.45943539,  0.70838129],
       [ 0.16226011,  0.75754607,  0.5772552 ,  0.19858199,  0.88720662]])

In [34]:
np.random.normal(0,1,10).reshape(2,5) #정규분포

array([[-0.94627876,  0.55522872, -0.5222648 ,  0.02386394,  0.19552232],
       [-0.2421058 ,  0.61000565,  0.43102976,  1.61064314,  0.69279736]])

### concatenate

In [35]:
a = np.array([[1,2,3]])
b = np.array([[2,4,5]])

In [38]:
#vstack
np.vstack((a,b))

array([[1, 2, 3],
       [2, 4, 5]])

In [39]:
#hastack
np.hstack((a,b))

array([[1, 2, 3, 2, 4, 5]])

## Comparison

### All & any

In [41]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.any(a>5) , np.all(a<0)

(True, False)

### np.where

In [47]:
#조건에 맞는 인덱스를 반환하다.
a = np.array([1,3,0])

In [49]:
#True 일때는 3 , False일때는 2
np.where(a>0,3,2)

array([3, 3, 2])

In [50]:
# index값을 반환한다.
np.where(a>0)

(array([0, 1], dtype=int64),)

### argmax & argmin

In [51]:
a = np.array([1,2,4,5,6,7,8])
np.argmax(a), np.argmin(a)

(6, 0)